config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  resources :comments
  devise_for :users
  get 'links/index'

  resources :links do
    member do
      get:delete
      put "like" ,   to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end

  root 'links#index'

  get 'links/show'

  get 'links/new'

  get 'links/create'

  get 'links/edit'

  get 'links/update'

  get 'links/delete'

  get 'links/destroy'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
end

app/models/googleuser2.rb
class Googleuser2 < ApplicationRecord

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |googleuser2|
      googleuser2.provider = auth.provider
      googleuser2.uid = auth.uid
      googleuser2.name = auth.info.name
      googleuser2.oauth_token = auth.credentials.token
      googleuser2.oauth_expires_at = Time.at(auth.credentials.expires_at)
      googleuser2.save!
    end
  end

end

app/models/link.rb
class Link < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_googleuser2

  def current_googleuser2
    @current_googleuser2 ||= Googleuser2.find(session[:googleuser2_id]) if session[:googleuser2_id]
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
  end

  def show
  end


  def edit
  end

  def create

    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user == current_user

      if @comment.save
         redirect_to(@link)
      else
        render('new')
      end
  end

  def destroy
    @comment.destroy
    redirect_to(:back)
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authenticate_user!, except: [:index,:show]
  def index
    @links = Link.all
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = current_user.links.build
  end

  def create
    @link = current_user.links.build(links_params)
    if @link.save
      flash[:notice]= "Success"
      redirect_to(links_path)
    else
      render('new')
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(links_params)
      redirect_to(link_path)
    else
      render('edit')
    end
  end

  def delete
    @link = Link.find(params[:id])
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to(links_path)
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_by current_user
    redirect_to :back
  end

  def links_params
    params.require(:link).permit(:title,:url)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    googleuser2 = Googleuser2.from_omniauth(env["omniauth.auth"])
    session[:googleuser2_id] = googleuser2.id
    redirect_to root_path

  end

  def destroy
    session[:googleuser2_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link_id %>
    <%= f.number_field :link_id %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>MillsFit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
      <div class="topnav">
        <b class="topnav b;" font-size="64px;" style=" font-family: Impact, Charcoal, sans-serif;"><%= link_to "MillsFit", root_path %></b>
          <% if current_googleuser2 %>
	      Signed in as <strong><%= current_googleuser2.name %></strong>!
              <a class="topnav a"><%= link_to 'Submit link', new_link_path %></a>
              <a class="topnav a"><%= link_to 'Account', edit_user_registration_path %></a>
              <a class="topnav a"><%= link_to "Sign out with Google", signout_path, id: "sign_out" %>
              <a class="topnav a"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></a>
          <% else -%>
              <a class="topnav a"><%= link_to 'Submit link', new_link_path %></a>
              <a class="topnav a"><%= link_to 'Sign up', new_user_registration_path %></a>
              <a class="topnav a"><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></a>
          <% end -%>
      </div>

  <div id="main_content" class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>

      <div id="content" class="col-md-9 center-block">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/links/create.html.erb
<h1>Links#create</h1>
<p>Find me in app/views/links/create.html.erb</p>

app/views/links/delete.html.erb
<%=link_to("Back To List", links_path) %>
<%= form_for(@link , :method => 'delete') do |f|%>
<p>Are you sure you want to delete the subject</p>
<%= f.submit("Delete")  %>
<% end %>

app/views/links/destroy.html.erb
<h1>Links#destroy</h1>
<p>Find me in app/views/links/destroy.html.erb</p>

app/views/links/edit.html.erb
<%= link_to("Back To List" , links_path)%>
<%=form_for @link do |f| %>
<%= f.label :Title %>
<%= f.text_field :title%><br/>
<%= f.label :URL%>
<%= f.text_field :url%><br/>
<%= f.submit("Submit")%>
<%end%>

app/views/links/index.html.erb
<% @links.each do |link| %>
  <div class="link row clearfix">
    <h2>
      <%= link_to link.title , link_path(link) %><br>
      <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.email %></small>
    </h2>
    <div class="btn-group">
       <a class="btn btn-default btn-sm" href="<%= link.url %>">Visit Link</a>
       <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
       <span class="glyphicon glyphicon-chevron-up"></span>
       Upvote
       <%= link.get_upvotes.size %>
       <% end %>
       <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
       <span class="glyphicon glyphicon-chevron-down">
       Downvote
       <%= link.get_downvotes.size %>
       <% end %>
    </div>
  </div>
<% end %>

app/views/links/new.html.erb
<%= link_to("Back To List" , links_path)%>
<%=form_for @link do |f| %>
  <%= f.label :Title %>
  <%= f.text_field :title%><br/>
  <%= f.label :URL%>
  <%= f.text_field :url%><br/>
  <%= f.submit("Submit")%>
  <%end%>

app/views/links/show.html.erb
<div class="page-header">
    <h1><a href="<%= @link.url %>"><%= @link.title %></a><br> <small>Submitted by <%= @link.user.email %></small></h1>
</div>

<div class="btn-group">
    <%= link_to 'Visit URL', @link.url, class: "btn btn-primary" %>
</div>

<div class="btn-group pull-right">
   <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
   <span class="glyphicon glyphicon-chevron-up"></span>
   Like
   <%= @link.get_upvotes.size %>
   <% end %>
   <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
   <span class="glyphicon glyphicon-chevron-down">
    Dislike
    <%= @link.get_downvotes.size %>
   <% end %>
</div>

<% if @link.user == current_user -%>
    <div class="btn-group">
      <%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default" %>
      <%= link_to 'Destroy', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
    </div>
<% end %>




  <% @link.comments.each do |comment|%>
      <div class="comments_wrapper clearfix">
         <div class="pull-left">
             <p class="lead"><%= comment.body %></p>
             <p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> by
             <%=@link.user.email%>
             </small></p>
         </div>
         <div class="btn-group pull-right">
           <% if @link.user == current_user -%>
             <%= link_to 'Destroy', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
           <%end%>
         </div>
      </div>
  <%end%>


  <%= simple_form_for [@link, Comment.new]  do |f| %>
      <div class="field">
           <%= f.text_area :body, class: "form-control" %>
      </div>  <br>
           <%= f.submit "Add Comment", class: "btn btn-primary" %>
    <% end %>

app/views/links/update.html.erb
<h1>Links#update</h1>
<p>Find me in app/views/links/update.html.erb</p>